### ISSUE TITLE
support GCC6 build

### ISSUE THREAD

**Issue by Icenowy** [Alcaro/minir#6]
```
diff --git a/rescompile.cpp b/rescompile.cpp
index 8e0fb37..2977a4a 100644
--- a/rescompile.cpp
+++ b/rescompile.cpp
@@ -203,7 +203,7 @@ void compileconfig(FILE * output)
        
        while (!feof(in))
        {
-#define error(why) do { printf("%s: "why"\n", linecopy); exit(1); } while(0)
+#define error(why) do { printf("%s: " why "\n", linecopy); exit(1); } while(0)
                char linebuf[1024];
                char linecopy[1024];
                char * line=linebuf;
```

For GCC6, between " and other literal a space must be inserted

**Comment by Alcaro** [comment]
I think minir is C++03, which doesn't require that... but maybe I forgot the compiler flag. Might as well fix it anyways, it does no harm. Thanks for the reminder.

**Comment by Icenowy** [comment]
For G++6 the default std is no longer 03. Seems that it's 14.

**Comment by Alcaro** [comment]
minir is supposed to be built with -std=c++98. But that specific file follows another set of build rules, and apparently I messed it up.
